### ISSUE TITLE
[bisected] Unresponsiveness and memleaks when pressing O in an SVG tab

### ISSUE THREAD

**Issue by MoSal** [cmcaine/tridactyl#879]
* Steps to reproduce:
 1. Don't try this in an underpowered device.
 2. `mv ~/.tridactylrc{,.dis}`
 3. Start Firefox beta with a new profile.
 4. Install a beta tridactyl build.
 5. `:tabnew https://api.travis-ci.org/cmcaine/tridactyl.svg` 
 6. `O`

* Tridactyl version (`:version`):

  + Regression bisected to rev 52f8cd706006c8bb98d6ed884c139b3cf65e38be. All builds since then are effected.

* Firefox version (Top right menu > Help > About Firefox):

  + Firefox beta / Linux x86_64 /  62.0b12 (64-bit)

**Comment by bovine3dom** [comment]
Oh, nice find. That's a good bug right there. Very high CPU load in Firefox 61 (no beta required).

I get `# TypeError: cmdline_iframe.focus is not a function` when I close the tab after. I suspect what is happening is that the command line isn't on the page, so `focus` isn't a function, and somehow Tridactyl gets stuck in a loop trying to call focus.

**Comment by glacambre** [comment]
Perhaps we should rethrow [here](https://github.com/cmcaine/tridactyl/blob/master/src/commandline_content.ts#L64) and await [here](https://github.com/cmcaine/tridactyl/blob/876050d410d7ce5bb5b63d2b4720298bd6caf53f/src/commandline_background.ts#L50).
